[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino

; Указываем кастомную строку для вызова avrdude при прожиге бутлоадера
board_bootloader.program = usr_isp
upload_protocol = stk500v1
upload_port = COM3
upload_speed = 19200

; Прописываем параметры вызова вручную, чтобы убрать "unknown"
upload_flags =
    -C
    ${platformio.packages_dir}/tool-avrdude/avrdude.conf
    -p
    m328p
    -c
    stk500v1
    -P
    COM3
    -b
    19200
    -F